//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace twiview.Locale {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("twiview.Locale.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Oops, something went wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popular Tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_Featured {
            get {
                return ResourceManager.GetString("Headline_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet&lt;small&gt;({0})&lt;/small&gt;Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_NoTweetToShow_HTML {
            get {
                return ResourceManager.GetString("Headline_NoTweetToShow_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline of @{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_Timeline {
            get {
                return ResourceManager.GetString("Headline_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The time taken to search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_TimeToSearch {
            get {
                return ResourceManager.GetString("Headline_TimeToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_UserNotFound {
            get {
                return ResourceManager.GetString("Headline_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweets of @{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Headline_UserTweet {
            get {
                return ResourceManager.GetString("Headline_UserTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popular Tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Featured {
            get {
                return ResourceManager.GetString("Menu_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in with Twitter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Tweets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_MyTweet {
            get {
                return ResourceManager.GetString("Menu_MyTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Timeline {
            get {
                return ResourceManager.GetString("Menu_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popularity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_Featured {
            get {
                return ResourceManager.GetString("Order_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Order_New {
            get {
                return ResourceManager.GetString("Order_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Datetimepicker {
            get {
                return ResourceManager.GetString("Pager_Datetimepicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Latest {
            get {
                return ResourceManager.GetString("Pager_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   « Newer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Newer {
            get {
                return ResourceManager.GetString("Pager_Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   « Next day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_NextDay {
            get {
                return ResourceManager.GetString("Pager_NextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide RT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_NoRT {
            get {
                return ResourceManager.GetString("Pager_NoRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Older » に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Older {
            get {
                return ResourceManager.GetString("Pager_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous day » に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_PreviousDay {
            get {
                return ResourceManager.GetString("Pager_PreviousDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Results per page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_ResultsPerPage {
            get {
                return ResourceManager.GetString("Pager_ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_Today {
            get {
                return ResourceManager.GetString("Pager_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show RT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Pager_WithRT {
            get {
                return ResourceManager.GetString("Pager_WithRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Popular Tweets Having Similar Images({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Featured {
            get {
                return ResourceManager.GetString("Title_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet({0}) Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_NoTweetToShow {
            get {
                return ResourceManager.GetString("Title_NoTweetToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet of @{0} Having Similar Images({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_OneTweet {
            get {
                return ResourceManager.GetString("Title_OneTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeline of @{0} Having Similar Images{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Timeline {
            get {
                return ResourceManager.GetString("Title_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_UserNotFound {
            get {
                return ResourceManager.GetString("Title_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweets of @{0} Having Similar Images{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_UserTweet {
            get {
                return ResourceManager.GetString("Title_UserTweet", resourceCulture);
            }
        }
    }
}
